### PR TITLE
Fix property combination logic

### PR DESCRIPTION
**Pull request by rhinoduck**
From the commit message:
> When both the 'trim_trailing_whitespace' and the 'insert_final_newline'
> properties were specified for a section, only the first one in the list
> was picked up. Both will be picked up now.

In search for related issues, I only found https://github.com/editorconfig/editorconfig/issues/149, which deals with `insert_final_newline` not working, but for a different reason. I am mentioning it here, because it should probably be closed as there should not be any more problems with `insert_final_newline` now.

### CODE REVIEW

**Comment by rhinoduck** [comment]
I can remove the braces if you want, as well as make other style or naming changes. The new logic itself is working fine for me in a custom build of the plugin I now use with npp; I tried testing other paths than just my use case too, and there did not seem to be any problems.

As "Allow edits from maintainers" is enabled for this pull request, I think you should also be able to add the style edits as new commits yourselves, and then squash everything back into one commit as you are merging the PR. I've never done this myself though, so I may be mistaken.

**Comment by xuhdev** [comment]
Thank you for your contribution! @ffes It's not a problem at all! Feel free to review. As long as you feel comfortable, we can merge it, as I barely have access to Windows.

**Comment by xuhdev** [comment]
@ffes Shall we merge?

**Comment by ffes** [comment]
Merging is fine by me.

BTW, did you see the e-mail I sent you?

**Comment by ffes** [comment]
Thanks for your contribution

**Comment by rhinoduck** [comment]
Glad I could give something back.

**Pull request merged**
