### PR TITLE
update dependencies: editorconfig 0.12.9, pcre 10.44

### PR DESCRIPTION
**Pull request by chcg**
Appveyor build fails because https://learn.microsoft.com/en-us/powershell/module/bitstransfer/start-bitstransfer?view=windowsserver2022-ps the -dynamic flag is just available on win11 and the corresponding server2022. Appveyor use https://learn.microsoft.com/en-us/powershell/module/bitstransfer/start-bitstransfer?view=windowsserver2019-ps ,see https://www.appveyor.com/docs/windows-images-software/ for Visual Studio 2022.

### CODE REVIEW

**Comment by ffes** [comment]
Looks good to me.

Just wondering if we still need to use appveyor? The builds from github action do the job nowadays.

**Comment by ffes** [comment]
Just noticed that 0.12.9 has been released recently. Could you update the PR to 0.12.9?

**Comment by chcg** [comment]
Compilation with 0.12.9 failed. Maybe due to updated cmake version of editorconfig-core.
Appveyor could be removed if it is replaced by GH actions. That needs to be done on the appveyor website for this project.

**Review by ffes — APPROVED** [review]
I wait for @xuhdev for his opinion on appveyor. Other then that looks good to me.

As always, thanks for your contribution.

**Comment by xuhdev** [comment]
I agree we can remove appveyor. I believe we kept the appveyor configuration there for a grace period when we transited to github actions (although seems I can no longer find the conversation on that).

Currently the appveyor test doesn't block merging any PRs. After you delete the appveyor conf file, I'll go ahread and shut down from the appveyor side.

**Comment by chcg** [comment]
@ffes Removed appveyor.yml .

**Comment by chcg** [comment]
Fixed the build  of edc 0.12.9 by also using cmake version 3.16.3 in this plugin

**Comment by xuhdev** [comment]
Once you merge I'll remove the integration. I feel it's better to make sure config in the master branch is synced with external CI settings :)

**Comment by ffes** [comment]
I've merged it. The appveyor integration can be removed. 

And @chcg, thanks for your contribution.

**Comment by xuhdev** [comment]
Integration removed 👌

**Pull request merged**
