### PR TITLE
Add command to show current config settings

### LINKED ISSUE #15: Show current active settings
Sometimes it is very useful to have some form of feedback which editorconfig settings are currently active. Adding a dialog/messagebox to show all those settings would solve this.

### PR DESCRIPTION
**Pull request by dail8859**
Closes #15

### CODE REVIEW

**Comment by dail8859** [comment]
Example:

**Comment by ffes** [comment]
Look good, but I didn't test it yet. Life has taken up a lot of time lately.

**Comment by dail8859** [comment]
@ffes No worries at all. Take your time.

**Comment by ffes** [comment]
Thanks for your contribution!

**Pull request merged**
