### PR TITLE
update base libs (PCRE,  editorconfig-core-c-) for appveyor build

### PR DESCRIPTION
**Pull request by chcg**
- update pcre 8.41 -> 8.42
- update editorconfig-core-c-0.12.1 -> editorconfig-core-c-0.12.2

### CODE REVIEW

**Comment by ViceIce** [comment]
This is obsolete with current PR #16. 😁

**Comment by xuhdev** [comment]
I'll close this then

**Comment by chcg** [comment]
Ok, if you don't plan to provide a final stable build before switching to pcre2.

**Comment by xuhdev** [comment]
We'll provide a stable build once the new script is ready.

**Pull request closed without merging**
