### PR TITLE
Add support for trim_trailing_whitespace

### LINKED ISSUE #2: Add support for trim_trailing_whitespace
I'm trying at the moment to get a file to recognize my .editorconfig file but it doesn't seem to recognize it. It may be user error. 

I've discovered this plugin because I would really like to have noteplad++ automatically trim whitespace on save without the use of a macro.

### PR DESCRIPTION
**Pull request by ffes**
Closes #2

### CODE REVIEW

**Comment by xuhdev** [comment]
It looks good: I'll do a detailed review next week when I can boot into Windows.

**Comment by xuhdev** [comment]
@ffes I'm trying to resolve some build issue on Windows right now. One of the issues is that the automatic replacing `/MD` flag with `/MT` does not work any more in cmake. Do you know how to do that? The original workaround is taken from [here](http://stackoverflow.com/questions/14172856/cmake-compile-with-mt-instead-of-md/14172871#14172871) and used [here](https://github.com/editorconfig/editorconfig-notepad-plus-plus/blob/master/src/CMakeLists.txt#L22).

**Comment by xuhdev** [comment]
I've added more explanation in the README about the building procedure: now it should be easier for you to build. I've also uploaded a new version to the Notepad++ plugin manager. Thanks for your contribution!

**Comment by ffes** [comment]
Any changes you could add a compiled version of the dll to the [release section](https://github.com/editorconfig/editorconfig-notepad-plus-plus/releases) of this repo?

**Comment by xuhdev** [comment]
here https://sourceforge.net/projects/editorconfig/files/EditorConfig-Notepad%2B%2B-Plugin/

**Comment by ffes** [comment]
My bad, I seem to forget about SF every time

**Pull request merged**
