### PR TITLE
Support charset

### LINKED ISSUE #41: Character Encoding not set as specified
Hi,
I can't believe that I am the only one to realize that this is not working, so probably I am doing something wrong:

I am using Notepad++ 8.1.5 (64bit), I have installed the EditorConfig plugin, I have created a .editorconfig file, in my case with this content:
```
[*]
charset = utf-8
indent_style = space
indent_size = 2
```

Now when I open another simple text file (no special characters or something) from the same folder, it still is interpreted as ANSI encoding.
When I click on "Show EditorConfig settings for this file" it correctly shows me the content of .editorconfig.

Any ideas what can be wrong?
Walterdrink

### PR DESCRIPTION
**Pull request by ffes**
This adds support for the `charset` property. It converts the current document to the right charset before saving it.

Fixes #41

### CODE REVIEW

**Comment by ffes** [comment]
The failure of the CI seems to be the same issue as #31

**Comment by xuhdev** [comment]
I see the error message:

>  The server did not return the file size. The URL might point to dynamic content. The Content-Length header is not available in the server's HTTP reply.

Maybe the `-Dynamic` flag should be turned on? https://learn.microsoft.com/en-us/powershell/module/bitstransfer/start-bitstransfer?view=windowsserver2022-ps

**Comment by ffes** [comment]
> Maybe the -Dynamic flag should be turned on?

That helped for GitHub Actions, thanks for the tip!

But for appveyor it doesn't work. It's PowerShell doesn't seem to recognise the `-Dynamic` flag

**Review by xuhdev — APPROVED** [review]
Not sure if we should eventually drop appveyor for this repo. Let's merge this first.

**Pull request merged**
