### PR TITLE
Add AboutBox

### PR DESCRIPTION
**Pull request by ffes**
This adds an AboutBox to the plug-in.

The AboutBox shows the version of the plug-in, the core it is linked with and a clickable link to the website of the project.

### CODE REVIEW

**Comment by xuhdev** [comment]
Thanks! I'll review it at the end of this week.

**Comment by xuhdev** [comment]
I guess there might be some compatibility issues here. It has failed to compile on my system:

```
DlgAbout.cpp
C:\Users\hong\Documents\xusrc\editorconfig-notepad-plus-plus\src\DlgAbout.cpp(40) : error C2665: 'swprintf' : none of the 2 overloads could convert all the argument types
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\swprintf.inl(85): could be 'int swprintf(wchar_t *,const wchar_t *,...)'
        C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\swprintf.inl(36): or       'int swprintf(wchar_t *,size_t,const wchar_t *,...)'
        while trying to match the argument list '(TCHAR [260], int, const char [9], int, int, int)'
C:\Users\hong\Documents\xusrc\editorconfig-notepad-plus-plus\src\DlgAbout.cpp(67) : error C2664: 'HINSTANCE ShellExecuteA(HWND,LPCSTR,LPCSTR,LPCSTR,LPCSTR,INT)' : cannot convert argument 2 from 'const wchar_t [5]' to 'LPCSTR'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by ffes** [comment]
I looked at the error messages and you are trying to build an ANSI version of the plugin. Since N++ 6 (Mar 2012) only the UNICODE versions of N++ has been released. Therefore I never tested or even compiled an ANSI version of any of my plugins and never had anyone asking for it.

I think it is safe to say that we can stop supporting the ANSI plugin.

At the moment they are busy trying to get a 64-bit version of N++ out. So when that is released compiling a 64-bit version of the plugin would make more sense. But we'll cross that bridge when we come to it. Not for now...

Could you try and compile a UNICODE version of the plugin?

**Comment by xuhdev** [comment]
Ah, I didn't notice that ANSI support has been dropped for so many years! For some reason, the statistics still show that the [ANSI version is more popular](https://sourceforge.net/projects/editorconfig/files/EditorConfig-Notepad++-Plugin/0.3.0/), which I don't understand why. Perhaps we can just drop it and make people switch.

**Comment by xuhdev** [comment]
Thanks! The ANSI version has now been dropped and a new version has been uploaded.

**Pull request merged**
